---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: pedell
  namespace: pedell
  labels:
    app: pedell
type: Opaque
data:
  MYSQL_USER: ${PEDELL_MYSQL_USER}
  MYSQL_PASSWORD: ${PEDELL_MYSQL_PASSWORD}
