---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: loopia
  namespace: loopia
  labels:
    app: loopia
type: Opaque
data:
  LOOPIA_USER: ${LOOPIA_USER}
  LOOPIA_PASS: ${LOOPIA_PASS}
