---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
type: Opaque
data:
  MONGODB_ROOT_USER: ${MONGODB_ROOT_USER}
  MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASS}
