---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: mongodb
  name: mongodb
  labels:
    app: mongodb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:${MONGODB_VERSION}
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: mongodb-pv-storage
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_ROOT_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_ROOT_PASSWORD
      volumes:
        - name: mongodb-pv-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
