---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: tabs
  namespace: tabs
  labels:
    app: tabs
type: Opaque
data:
  MYSQL_PASSWORD: ${TABS_MYSQL_PASS}
