---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: rootsy
  namespace: rootsy
  labels:
    app: rootsy
type: Opaque
data:
  SPOTIFY_KEY: ${ROOTSY_SPOTIFY_KEY}
  SPOTIFY_SECRET: ${ROOTSY_SPOTIFY_SECRET}
  AUTH_USERNAME: ${ROOTSY_AUTH_USERNAME}
  AUTH_PASSWORD: ${ROOTSY_AUTH_PASSWORD}
