---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
