---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: unifi
  namespace: unifi
  labels:
    app: unifi
type: Opaque
data:
  MONGO_USER: ${UNIFI_MONGODB_USER}
  MONGO_PASSWORD: ${UNIFI_MONGODB_PASS}
