---
apiVersion: v1
kind: Service
metadata:
  name: dgraph-zero
  namespace: dgraph
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: grpc-zero
      port: 5080
    - protocol: TCP
      name: http-zero
      port: 6080
  selector:
    app: dgraph-zero
